// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: query.sql

package data

import (
	"context"
)

const getDataByKey = `-- name: GetDataByKey :one
SELECT uid, key, value FROM data
WHERE key = ? LIMIT 1
`

func (q *Queries) GetDataByKey(ctx context.Context, key string) (Datum, error) {
	row := q.db.QueryRowContext(ctx, getDataByKey, key)
	var i Datum
	err := row.Scan(&i.Uid, &i.Key, &i.Value)
	return i, err
}
